### PR TITLE
Make library independend of jQuery and compatible with Node

### PR DESCRIPTION
**Pull request by tnajdek**
The main reason for this changes is to make libZoteroJS work outside of the browser, primary for usage in Node and/or io.js. A side bonus is that the library no longer depends on jQuery.

Because libZoteroJS itself uses some es6 features, harmony and experimental features need to be enable in Node in order for this to work out of the box:

    node --harmony --harmony_default_parameters

Comprehensive summary of changes:

* Remove embedded third-party libraries and switch to npm for dependency management
* Introduce common js modules pattern, switch build from concatenation to browserify
* Replace dependency on jQuery's deferred with a [stand-alone deferred](https://github.com/medikoo/deferred) implementation
* Replace dependency on jQuery's `.text()` with a tiny striptags lib
* Replace dependency on other bits of jQuery by replacing jQuery bits with vanilla js
* Introduce xhr drop-in replacement for Node
* Switch to eslint, fix linting issues, unify which quotes are used for string

Adding extra libs impacted the build by few extra KBs but imho the benefits outweight this cost.

### CODE REVIEW

**Comment by fcheslack** [comment]
is there a benefit to using browserify over babel, which I've been using for the web library? Would either babel, or different options to browserify remove the need for node to be run with harmony features enabled?

**Comment by tnajdek** [comment]
It still uses babel for transpilation for the web, this is done as a transform within browserify. We need browserfiy to support node's `require()` and compile multiple source files into a single js file for the web - this has previously been done with concatenation.

We need `--harmony --harmony_default_parameters` because we don't transpile for node (only for browsers). However, if you think that's a problem I'd be happy to tweak the build system to produce another build for node.

**Comment by fcheslack** [comment]
I wasn't sure if babel could also bundle the way browserify does since it lists support for ES2015 modules, but I guess that's just syntax, not bundling.

Is there a downside to also transpiling for node? I don't think it's particularly a problem, especially now that node has re-merged. If there's no downside though, there are still old node installations that don't support --harmony, as well as an increasing number of alternative JS engines that may not support the es6 features.

**Comment by fcheslack** [comment]
Aside from the couple of nitpicks, this looks awesome. This is something I've wanted for quite a while.

**Comment by tnajdek** [comment]
Cool, glad you like it.

Answering your earlier question, we should be ok transpiling for Node, I would hope we can do sourcemaps so it's nicer to work with. As soon as I can spend some time on this, I'll look into that.

Any other questions, just let me know.

**Pull request merged**
